nemi = read.table('n-emi-sentence-freq.tbl')
novx = read.table('n-emi-no-vx-sentence-freq.tbl')
efsf = read.table('n-emi-no-vx-sentence-EF-SF-freq.tbl')
library(cairoDevice)
Cairo_pdf("fig4-1.pdf")
plot(nemi[1:20,2], nemi[1:20,1],xlab="절의 개수",ylab="빈도",type="b",ylim=c(0,170000))
points(efsf[1:20,2],efsf[1:20,1],pch=16,type="b")
points(novx[1:20,2],novx[1:20,1],pch=17,type="b")
legend("topright", c("emi", "novx", "efsf"), pch=c(1,17,16))
